spring:
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/message
        - id: chatModule1
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/message
        - id: chatModule2
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/ws/info/**
        - id: chatModule3
          uri: lb:ws://chat-server
          predicates:
            - Path=/chat-server/ws/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true