spring:
  application.name: catalog
  datasource:
    url: jdbc:mysql://localhost:3306/catalog?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      bindings:
        out-inventory_product_created:
          destination: inventory_product_created_topic
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
    config:
      username: hoang
      password: hoang
      uri: http://localhost:8888
      enabled: false
      import-check:
        enabled: false
  security.oauth2.resourceserver:
    jwt:
      issuer-uri: ${ISSUER_URI:http://localhost:8082/api/auth}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  main.allow-bean-definition-overriding: true
server:
  port: 8086

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
graphql:
  servlet:
    mapping: /api/v1/graphql

grpc:
  server:
    port: 2000

server.servlet.context-path: /api/catalog