version: '3.4'

services:
  config-server:
    container_name: config-server
    build:
      dockerfile: Dockerfile
      context: ./
      target: java
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=config-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SERVER_PORT=8888
    working_dir: /microservices
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
        reservations:
          cpus: "0.5"
          memory: "512M"


  discovery-server:
    container_name: discovery-server
    build:
      dockerfile: Dockerfile
      context: ./
      target: java
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=discovery-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - WAIT_SERVICE=config-server:8888
      - SERVER_PORT=8761
    working_dir: /microservices
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
        reservations:
          cpus: "0.5"
          memory: "512M"

  gateway-server:
    container_name: gateway-server
    build:
      dockerfile: Dockerfile
      context: ./
      target: java
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=gateway-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - WAIT_SERVICE=config-server:8888 discovery-server:8761
      - SERVER_PORT=8000
    working_dir: /microservices
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
        reservations:
          cpus: "0.5"
          memory: "512M"

  auth-server:
    container_name: auth-server
    build:
      dockerfile: Dockerfile
      context: ./
      target: java
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=auth-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - WAIT_SERVICE=config-server:8888 discovery-server:8761 gateway-server:8000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_server?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis
      - SERVER_PORT=8082
    working_dir: /microservices
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "4096M"
        reservations:
          cpus: "0.5"
          memory: "512M"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    networks:
      - default-network

  redis:
    image: redis:latest
    networks:
      - default-network

  neo4j:
    image: neo4j:latest
    networks:
      - default-network
  nginx:
    container_name: nginx
    image: nginx:1.17.10
    networks:
      - default-network
    ports:
      - "80:80"
    volumes:
      - ./_nginx:/etc/nginx/conf.d/
  axon-server:
    image: axoniq/axonserver
    hostname: axon-server
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - default-network


networks:
  default-network:
    driver: bridge

volumes:
  m2_data: { }