version: '2.2'

services:
  config-server:
    container_name: config-server
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=config-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
    working_dir: /microservices
    mem_limit: 1024m
    mem_reservation: 512m
    cpus: 1

  discovery-server:
    container_name: discovery-server
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8761:8761"
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=discovery-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - WAIT_SERVICE=config-server:8888
    working_dir: /microservices
    mem_limit: 1024m
    mem_reservation: 512m
    cpus: 1
    depends_on:
      - config-server

  gateway-server:
    container_name: gateway-server
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8000:8000"
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=gateway-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - WAIT_SERVICE=config-server:8888 discovery-server:8761
    working_dir: /microservices
    mem_limit: 1024m
    mem_reservation: 512m
    cpus: 1
    depends_on:
      - config-server
      - discovery-server

  auth-server:
    container_name: auth-server
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - default-network
    volumes:
      - .:/microservices
      - m2_data:/root/.m2/repository
    environment:
      - DIR=auth-server
      - JAVA_OPTS=-Xms1024M -Xmx2024M
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - WAIT_SERVICE=config-server:8888 discovery-server:8761 gateway-server:8000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_server?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis
    working_dir: /microservices
    mem_limit: 2048m
    mem_reservation: 512m
    cpus: 1
    depends_on:
      - config-server
      - discovery-server
      - gateway-server

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - default-network

  redis:
    image: redis:latest
    networks:
      - default-network

  neo4j:
    image: neo4j:latest
    networks:
      - default-network



networks:
  default-network:
    driver: bridge

volumes:
  m2_data: { }