spring:
  cache:
    redis:
      time-to-live: 1m
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true

file:
  upload-dir: ./upload