spring:
  cache:
    redis:
      time-to-live: 1m
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /auth-server
grpc:
  server:
    port: 1900
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true