security:
  oauth2:
    resource:
      token-info-uri: http://auth-server/auth-server/oauth/check_token
      user-info-uri: http://auth-server/auth-server/api/v1/user/me
      id: patient-service
    client:
      client-id: hoang
      client-secret: 1
      access-token-uri: http://auth-server/auth-server/oauth/token
      scope: read
spring:
  data:
    mongodb:
      database: patient-service
      host: localhost
      port: 27017
server:
  port: 8089
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
grpc:
  client:
    auth-server:
      address: 'discovery:///auth-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    catalog-service:
      address: 'discovery:///catalog-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

ribbon:
  http:
    client:
      enabled: true

