security:
  oauth2:
    resource:
      token-info-uri: http://auth-server/auth-server/oauth/check_token
      user-info-uri: http://auth-server/auth-server/api/v1/user/me
      id: file-service
    client:
      client-id: hoang
      client-secret: 1
      access-token-uri: http://auth-server/auth-server/oauth/token
      scope:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_service?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  http:
    client:
      enabled: true
file:
  upload-dir: ./upload
