spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saga?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000
