#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8082/auth-server/oauth/check_token
#      user-info-uri: http://localhost:8082/auth-server/api/v1/user/me
#      id: chat-server
#    client:
#      client-id: hoang
#      client-secret: 1
#      access-token-uri: http://localhost:8082/auth-server/oauth/token
#      scope: read
#server:
#  port: 8085
#
#eureka:
#  client:
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
