management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  security:
    oauth2:
      client:
        registration:
          hoang:
            clientId: hoang
            clientSecret: 1
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - read
              - write
              - server
            clientName: chat-server
        provider:
          hoang:
            authorizationUri: http://192.168.1.244:8000/auth-server/oauth/authorize
            tokenUri: http://192.168.1.244:8000/auth-server/oauth/token
            userInfoUri: http://192.168.1.244:8000/auth-server/api/v1/user/me
            userNameAttribute: username
security:
  oauth2:
    resource:
      token-info-uri: http://auth-server/auth-server/oauth/check_token
      user-info-uri: http://auth-server/auth-server/api/v1/user/me
      id: chat-server
    client:
      client-id: hoang
      client-secret: 1
      access-token-uri: http://auth-server/auth-server/oauth/token
      scope: read
      id: chat-server
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
ribbon:
  eureka:
    enabled: true
